In [48]:
import numpy as np #NumPy, Python'da sayısal hesaplamalar için çok güçlü ve verimli bir kütüphanedir.
arr = np.array([1,2,3,4,5])
arr

array([1, 2, 3, 4, 5])

In [50]:
#Find dimension of array
multi_list = [[1,2],[3,4],[5,6]]
multi_array = np.array(multi_list)
multi_array.ndim #it gives dimesnsion number

2

In [52]:
#Find type of array
list1 = [1,2,3]
list2 = ["Ali","Mustafa","Kenan"]
multi_array_1 = np.array(list1)
multi_array_2 = np.array(list2)
#gives type of array
multi_array_1.dtype
multi_array_2.dtype #U means unicodeString and number means max character

dtype('<U7')

In [54]:
#create array with 0's
array = np.zeros(5)
array #they are float

#type convertsion
array = array.astype(np.int64)
array

array2 = np.array([1,2,3], dtype = np.float64) #can describe type as parameter
array2

array([1., 2., 3.])

In [56]:
#Arithmetic operations
list_a = [[1,2,3], [4,5,6]]
list_b = [[7,8,9], [10,11,12]]
array_a = np.array(list_a)
array_b = np.array(list_b)

array_a + array_b #matrix toplama gibi aynı indexler toplanır (aynı sayıda eleman olduğunda)

array_a * 2 #her elemanını 2 ile çarpar

array([[ 2,  4,  6],
       [ 8, 10, 12]])

In [58]:
#Comparing arrays

res = array_a > array_b #elemanları indexlerine göre kıyaslar ve her eleman için true/false değeri verir
res.dtype #sonuçların tutulduğu True/False arrayi

dtype('bool')

In [69]:
arr = np.array([[1,2,3],[4,5,6]])
arr[1,2] #multi-dimensional indexing

6

In [73]:
multi_array = np.array([[1,2,3],[4,5,6],[7,8,9]])
#slicing multi-dimensional array
multi_array[1:3,1:3] #tablo çiz, istenen bölge için önce row ele; ardından column ele

array([[5, 6],
       [8, 9]])

In [79]:
#fancy indexing
multi_array = np.array([[1,2,3],[4,5,6],[7,8,9]])

multi_array[[0,0,2,2],[0,2,0,2]] #köşeleri verir. Instead giving only value, we describe rown and column

array([1, 3, 7, 9])

In [83]:
#Boolean indexing
multi_array = np.array([[1,2,3],[4,5,6],[7,8,9]])

multi_array[multi_array > 5] #conditional indexing (gives values which is true)

array([6, 7, 8, 9])

In [91]:
#Broadcast: Tablolar aynı değilse küçük olan expand olur 
multi_array_1 = np.array([[1,2,3],[4,5,6],[7,8,9]])
multi_array_2 = np.array([1,2,3])

multi_array_1 + multi_array_2 #işlem tom rowlara aynı değerler ile yapıldı

array([[ 2,  4,  6],
       [ 5,  7,  9],
       [ 8, 10, 12]])

In [141]:
#creating series with pandas
from pandas import Series #pandas series uses numpy array

s = Series([1,3,5,7,9]) #values with indexes 0-n
s[3] #index numarası girip value alıyoruz

s.values #gives array
s.index #gives rangeIndex

#indexi biz verebiliriz
s = Series([2,3,4,5], index = [1,2,3,4]) #index e girilen değerler string de olabilir
s

#python dict kullanarak da Series oluşturabilirisin
s = Series({'a':100, 'b':200, 'c':300}) #key ler index, value lar value olur
s

#Series methods and attributes
s = Series([1,2,3,3,5,7,1,4,9])
s

#Series methods
s.sum()
s.product() #tüm elemanlar çarpar
s.mean() #ortalama alır

#Series attributes
s.dtype
s.ndim #dimension
s.size
s.index #gives rangeIndex
s.values #gives value array (numpy array)
type(s.values) #numpy.ndarray

numpy.ndarray

In [185]:
#DataFrame (tabular) with pandas: Used with multi-dimensional array
#columns can be different data type

#in real world app you dont need to create dataFrame becasue they are used to load data from file
from pandas import DataFrame

people = {'name': ['Ali', 'Mustafa', 'Arda'], 'age': [12,24,35]}
frame = DataFrame(people, columns = ['age', 'name', 'places']) #you can change column order, also can add extra column(NaN)
frame

frame['age'] #or frame.age

frame.loc[1] #gives row acording to index

frame.places = 'ISTANBUL' #columndaki tüm rowlar aynı değer olur
frame

#adding values to column
places = Series(['Ardahan', 'Manisa', 'Sivas'])
places
frame.places = places
frame

#column silme
del frame['places']
frame

#reindexing: reindexing Series or DataFrames
s = Series([1,2,3,4,5], index = ['c', 'a','b','d', 'e'])
s = s.reindex(['a', 'b', 'c', 'd', 'e']) #indexler valuelar ile birlikte değişti
s

#np nin bizim için multi-dimensional aarray oluşturmasını isteyeceğiz
d = DataFrame(np.arange(9).reshape((3,3)), index = ['c', 'a', 'b'], columns = ['apple', 'mango', 'banana'])
d

d = d.reindex(['a','b','c'])
d

d = d.reindex(columns = ['banana', 'apple', 'mango'])
d

banana  apple  mango
a       5      3      4
b       8      6      7
c       2      0      1

In [197]:
#arithmetic operations with fill values
s1 = Series([10,20,30,40,50,60,70,80], index = [1,2,3,4,5,6,7,8])
s2 = Series([10,20,30,40,50], index = [1,2,3,4,5])

s1 + s2 #index 6,7,8 will be NaN

s1.add(s2, fill_value = 0) #NaN olanlar fill_value ile 0 a eşitleyip + operatoru işlevini kullandık

d1 = DataFrame(np.arange(9).reshape((3,3)), columns = ['a', 'b', 'c'])
d2 = DataFrame(np.arange(20).reshape((4,5)), columns = ['a', 'b', 'c', 'd', 'e'])

d1.add(d2, fill_value = 0) #NaN olanlar fill_value ile 0 a eşitleyip + operatoru işlevini kullandık

a     b     c     d     e
0   0.0   2.0   4.0   3.0   4.0
1   8.0  10.0  12.0   8.0   9.0
2  16.0  18.0  20.0  13.0  14.0
3  15.0  16.0  17.0  18.0  19.0

In [205]:
#Arithmetic operation with series and DataFrames
from pandas import Series, DataFrame
s = Series([1,2,3,4])
d = DataFrame(np.arange(8).reshape(2,4))

d + s #broadcasting (s aynı rowdan bir tane daha üretir)

0  1  2   3
0  1  3  5   7
1  5  7  9  11

In [213]:
#Python function that applied to data set
d = DataFrame(np.arange(16).reshape(4,4))
d

f = lambda x: x+10
d.apply(f) #Data set elemanlarına function uygulama

0   1   2   3
0  10  11  12  13
1  14  15  16  17
2  18  19  20  21
3  22  23  24  25

In [247]:
#sorting: like rearrange but this is automatically
s = Series([1,2,3,4], index=[2,4,1,3])

s.sort_index() #sort as looking indexes

d = DataFrame(np.arange(16).reshape(4,4), index =['c', 'a', 'b', 'd'], columns = [2, 1, 3, 4])

d.sort_index() #sort as rows
d.sort_index(axis = 1) #sort as columns

d.sort_index(ascending = False) #tersen sıralama
d.sort_index(axis = 1, ascending = False) #sort as columns

#sort with values
s = Series([1000,200,300,40])
s.sort_values()

d = DataFrame({"name":['Laptop','Phone','PC'], "price":[30,20,30]})
d

d.sort_values(by='price', ascending = False)

name  price
0  Laptop     30
2      PC     30
1   Phone     20

In [255]:
#finding duplicate index
s = Series([1,2,3,4,5], index=['a','b','b','d','e'])
s

s.index.is_unique #Series teki tüm indexler unique mi

False

In [261]:
#statistical methods
d = DataFrame({"name":['Laptop','Phone','PC'], "price":[30,20,30]})

#sum içine axis = 1 verirsen rowları toplar(rowdaki veri tipleri aynı olmalı)
d.sum() #tüm columnları ayrı ayrı toplar

d.count() #columların ayrı ayrı sayısını verir

d.describe() #tablo hakkında bilgi verir

price
count   3.000000
mean   26.666667
std     5.773503
min    20.000000
25%    25.000000
50%    30.000000
75%    30.000000
max    30.000000